development:
 adapter: mysql2
 database: muddleme_development
 username: root
 password: db123@
 host: localhost
 reconnect: true

staging:
 adapter: mysql2
 database: muddleme_staging
 username: root
 password: db123@
 host: localhost
 reconnect: true

production:
 adapter: mysql2
 database: muddleme_production
 username: root 
 password: db123@
 host: localhost
 reconnect: true
